<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>vindOS</AssemblyName>
    <RootNamespace>VindOS</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>0.1.0</Version>
    <ApplicationIcon>vindOS.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="vindOS.ico" />
    <Resource Include="vindOS.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="native\*.dll" CopyToOutputDirectory="PreserveNewest" Link="%(Filename)%(Extension)" />
    <None Include="..\vendor\NvStreamManagerClient.dll" CopyToOutputDirectory="PreserveNewest" Link="Server\NvStreamManagerClient.dll" Condition="'$(_IsPublishing)' != 'true'" />
    <None Include="..\vendor\Server\**\*" CopyToOutputDirectory="PreserveNewest" Link="Server\%(RecursiveDir)%(Filename)%(Extension)" Condition="'$(_IsPublishing)' != 'true'" />
    <None Include="..\vendor\opencomposite\openvr_api.dll" CopyToOutputDirectory="PreserveNewest" Link="opencomposite\openvr_api.dll" />
  </ItemGroup>
</Project>
